name: Docker Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-integration:
    name: Docker Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu:22.04, debian:bullseye, fedora:37, centos:stream9]
        arch: [amd64, arm64]
        include:
          - os: ubuntu:22.04
            arch: amd64
          - os: ubuntu:22.04
            arch: arm64
          - os: debian:bullseye
            arch: amd64
          - os: debian:bullseye
            arch: arm64
          - os: fedora:37
            arch: amd64
          - os: fedora:37
            arch: arm64
          - os: centos:stream9
            arch: amd64
          - os: centos:stream9
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build and run tests
        run: |
          # Build the Docker image
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --build-arg BASE_IMAGE=${{ matrix.os }} \
            -t libvirt-test-${{ matrix.os }}-${{ matrix.arch }} \
            --load \
            .

          # Run the container with necessary privileges
          docker run --rm \
            --platform linux/${{ matrix.arch }} \
            --privileged \
            -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock \
            -v /var/lib/libvirt:/var/lib/libvirt \
            libvirt-test-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.os }}-${{ matrix.arch }}
          path: test-artifacts/
          retention-days: 7 